<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="root.local" failures="4" tests="4" name="Surefire test" time="4.858" errors="0" timestamp="2021-06-14T03:00:56 EDT">
  <testcase classname="com.equifax1.testcases.TestDELETE" name="createEmployee" time="1.85">
    <failure type="io.restassured.path.json.exception.JsonPathException" message="Failed to parse the JSON document">
      <![CDATA[io.restassured.path.json.exception.JsonPathException: Failed to parse the JSON document
at io.restassured.path.json.JsonPath$ExceptionCatcher.invoke(JsonPath.java:1002)
at io.restassured.path.json.JsonPath$4.doParseWith(JsonPath.java:967)
at io.restassured.path.json.JsonPath$JsonParser.parseWith(JsonPath.java:1047)
at io.restassured.path.json.JsonPath.get(JsonPath.java:202)
at com.equifax1.testcases.TestDELETE.createEmployee(TestDELETE.java:44)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
Caused by: groovy.json.JsonException: Lexing failed on line: 1, column: 1, while reading '<', no possible valid JSON value or punctuation could be recognized.
at groovy.json.JsonLexer.nextToken(JsonLexer.java:86)
at groovy.json.JsonLexer$nextToken.call(Unknown Source)
at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:115)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:119)
at io.restassured.internal.path.json.ConfigurableJsonSlurper.parse(ConfigurableJsonSlurper.groovy:97)
at io.restassured.internal.path.json.ConfigurableJsonSlurper$parse.callCurrent(Unknown Source)
at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:51)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:156)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:168)
at io.restassured.internal.path.json.ConfigurableJsonSlurper.parseText(ConfigurableJsonSlurper.groovy:83)
at io.restassured.path.json.JsonPath$4$1.method(JsonPath.java:965)
at io.restassured.path.json.JsonPath$ExceptionCatcher.invoke(JsonPath.java:1000)
... 36 more
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- createEmployee -->
  <testcase classname="com.equifax1.testcases.TestGET" name="getWeatherDetails" time="0.63">
    <failure type="java.lang.AssertionError" message="expected:&amp;lt;429&amp;gt; but was:&amp;lt;200&amp;gt;">
      <![CDATA[java.lang.AssertionError: expected:<429> but was:<200>
at com.equifax1.testcases.TestGET.getWeatherDetails(TestGET.java:29)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
... Removed 36 stack frames]]>
    </failure>
  </testcase> <!-- getWeatherDetails -->
  <testcase classname="com.equifax1.testcases.TestCreate" name="addPostNewEmpoyee" time="0.913">
    <failure type="java.lang.AssertionError" message="expected:&amp;lt;false&amp;gt; but was:&amp;lt;true&amp;gt;">
      <![CDATA[java.lang.AssertionError: expected:<false> but was:<true>
at com.equifax1.testcases.TestCreate.addPostNewEmpoyee(TestCreate.java:64)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
... Removed 36 stack frames]]>
    </failure>
  </testcase> <!-- addPostNewEmpoyee -->
  <testcase classname="com.equifax1.testcases.TestCreate" name="addPostNewEmpoyee" time="0.809">
    <failure type="java.lang.AssertionError" message="expected:&amp;lt;false&amp;gt; but was:&amp;lt;true&amp;gt;">
      <![CDATA[java.lang.AssertionError: expected:<false> but was:<true>
at com.equifax1.testcases.TestCreate.addPostNewEmpoyee(TestCreate.java:64)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
... Removed 36 stack frames]]>
    </failure>
  </testcase> <!-- addPostNewEmpoyee -->
</testsuite> <!-- Surefire test -->
